# Generated by Django 5.2.7 on 2025-10-04 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("church_app", "0001_initial"),
    ]

    operations = []
