# Generated by Django 5.2.7 on 2025-10-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("church_app", "0002_auto_20251004_2334"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prayerrequest",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
