# Generated by Django 5.2.7 on 2025-12-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("church_app", "0004_bannerslide"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="prayer",
            options={},
        ),
        migrations.AddField(
            model_name="prayer",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="prayer",
            name="category",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="prayer",
            name="language",
            field=models.CharField(default="english", max_length=20),
        ),
    ]
