# Generated by Django 5.2.7 on 2025-12-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("church_app", "0005_alter_prayer_options_prayer_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bannerslide",
            name="image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="gallery",
            name="image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="bannerslide",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="banners/"),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="video_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
