# Generated by Django 5.2.7 on 2025-12-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("church_app", "0006_bannerslide_image_url_event_image_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bannerslide",
            name="subtitle",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
