# Generated by Django 5.2.7 on 2025-12-21 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("church_app", "0007_alter_bannerslide_subtitle"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParishGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("youth", "Youth Group"),
                            ("vincent", "Vincent de Paul"),
                            ("legion", "Legion of Mary"),
                            ("joseph", "St. Joseph Group"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Leave blank to use default static content",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GroupActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="group_activities/"
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="church_app.parishgroup",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
