# Generated by Django 5.2.7 on 2025-12-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("church_app", "0008_parishgroup_groupactivity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupactivity",
            name="date",
            field=models.DateField(),
        ),
    ]
