# Generated by Django 5.2.7 on 2025-12-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("church_app", "0009_alter_groupactivity_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="parishgroup",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="group_logos/"),
        ),
    ]
