# Generated by Django 5.2.7 on 2025-12-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("church_app", "0010_parishgroup_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallery",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="gallery_videos/"),
        ),
    ]
