# Generated by Django 4.2.23 on 2025-12-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("church_app", "0011_gallery_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bannerslide",
            name="title",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
